In [1]:
import pandas as pd
import time
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("CKD.csv") # Reading the dataset

In [3]:
df.head()

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             399 non-null    float64
 1   bp              399 non-null    float64
 2   sg              399 non-null    object
 3   al              399 non-null    float64
 4   su              399 non-null    float64
 5   rbc             399 non-null    object
 6   pc              399 non-null    object
 7   pcc             399 non-null    object
 8   ba              399 non-null    object
 9   bgr             399 non-null    float64
 10  bu              399 non-null    float64
 11  sc              399 non-null    float64
 12  sod             399 non-null    float64
 13  pot             399 non-null    float64
 14  hrmo            399 non-null    float64
 15  pcv             399 non-null    float64
 16  wc              399 non-null    float64
 17  rc              399 non-null    float64
 18  htn             399 non-null    object
 19  dm              399 non-null    object
 20  cad             399 non-null    object
 21  appet           399 non-null    object
 22  pe              399 non-null    object
 23  ane             399 non-null    object
 24  classification  399 non-null    object
dtypes: float64(13), object(12)
memory usage: 78.1+ KB

In [5]:
df.isnull().sum()

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hrmo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [8]:
df.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [13]:
df['classification'].value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [15]:
dataset=pd.get_dummies(df,drop_first=True,dtype="int")

In [17]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,sg_b,sg_c,sg_d,sg_e,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597,0,1,0,0,1,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,12300.000000,4.705597,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,8408.191126,4.705597,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,8408.191126,4.705597,0,0,1,0,1,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,12400.000000,4.705597,0,1,0,0,1,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,37.000000,9800.000000,4.400000,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,27.000000,8408.191126,4.705597,0,1,0,0,1,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,26.000000,9200.000000,3.400000,0,1,0,0,1,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,38.868902,8408.191126,4.705597,0,0,0,0,1,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,53.000000,8500.000000,4.900000,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0

In [19]:
X= dataset.iloc[:,:-1].to_numpy()
y= dataset.iloc[:,-1].to_numpy()

In [21]:
X.shape

(399, 27)

In [23]:
# Split data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [24]:
y_train.mean()

0.6300940438871473

In [25]:
y_test.mean()

0.6

In [29]:
# Performing standard scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### Naive Bayes (probabilistic classification algorithm) : Naive Bayes is mainly used for classification problems, not for regression. It works on the principle of Bayes' Theorem and assumes that features are independent (which is often not true in real-world scenarios, but it still performs well).

#### For Binary Classification: Use BernoulliNB or GaussianNB depending on whether your data is binary or continuous.

#### For Multiclass Classification: Use MultinomialNB if working with text or categorical data.

#### For Continuous Data in Multiclass: Use GaussianNB.

In [32]:
import pickle
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import BernoulliNB

# Define algorithms and parameter grids
algorithms = {
    'LogisticRegression': {
        'model': LogisticRegression(),
        'params': {
            'C': [0.01, 0.1, 1, 10],
            'penalty' : ['l1', 'l2', 'elasticnet'],
            'solver': ['liblinear', 'lbfgs'],
            'max_iter': [100, 200]
        }
    },
   'SVM': {
        'model': SVC(),
        'params': {
            'C': [0.1, 1, 10],
            'kernel': ['linear', 'rbf', 'poly'],
            'gamma': ['scale', 'auto']
        }
    },
    'DecisionTree': {
        'model': DecisionTreeClassifier(),
        'params': {
            'criterion': ['gini', 'entropy','log_loss'],
            'splitter':['best', 'random'],
            'max_depth': [5, 10, 20],
            'min_samples_split': [2, 5, 10],
            'min_samples_leaf': [1, 5, 10]
        }
    },
    'RandomForest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [100, 150, 200],
            'max_depth': [10, 20, None],
            'criterion': ['gini', 'entropy','log_loss'],
            'max_features': ['sqrt', 'log2'],
            'ccp_alpha': [0.0, 0.01, 0.1, 1.0]
        }
    },  
    'GradientBoosting': {
        'model': GradientBoostingClassifier(),
        'params': {
            'n_estimators': [100, 150, 200],
            'learning_rate': [0.01, 0.1, 1],
            'max_depth': [3, 5, 7],
            'min_samples_split': [2, 5, 10]
        }
    },
    'XGBoost': {
        'model': XGBClassifier(),
        'params': {
            'n_estimators': [100, 150, 200],
            'learning_rate': [0.01, 0.1, 1],
            'max_depth': [3, 5, 7],
            'min_child_weight': [1, 3, 5]
        }
    },
    'KNN': {
        'model': KNeighborsClassifier(),
        'params': {
            'n_neighbors': [3, 5, 7, 9],  # sqrt(399)= 19.97 ==> so we need to consider 19 or 21 as n_neighbors.399 is total number of rows in the dataset.
            'weights': ['uniform', 'distance'],
            'algorithm': ['ball_tree', 'kd_tree', 'brute'],
            'p': [1, 2]
        }
    },
    'BernoulliNB': {
        'model': BernoulliNB(),
        'params': {
            'alpha': [0.1, 0.5, 1.0],
            'binarize': [0.0, 0.5, 1.0]
        }
    }
}

In [34]:

# Initialize results dictionary to store model performance
results = {}
start = time.time()

# Perform Grid Search for each algorithm
for algo_name, config in algorithms.items():
    print(f"Training {algo_name}...")
    grid = GridSearchCV(
        estimator=config['model'],
        param_grid=config['params'],
        scoring='accuracy',
        refit=True,
        cv=4,
        verbose=1,
        n_jobs=-1
    )
    grid.fit(X_train, y_train)
    
    # Predict on test data
    y_pred = grid.predict(X_test)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_pred) # Use ROC-AUC if you care about overall model performance across all classification thresholds.
    f1_weighted = f1_score(y_test, y_pred, average='weighted') #Use F1 Score if you care about both false positives and false negatives.
    
    # Store results
    results[algo_name] = {
        'best_params': grid.best_params_,
        'accuracy': accuracy,
        'f1weighted' : f1_weighted,
        'precision': precision,
        'recall': recall,
        'roc_auc': roc_auc,
        'best_model': grid.best_estimator_
    }

end = time.time()
print('Time taken in grid search: %0.2f seconds'%(end-start))

Training LogisticRegression...
Fitting 4 folds for each of 48 candidates, totalling 192 fits

C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
96 fits failed out of a total of 192.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
32 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 67, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
32 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 75, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
32 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 67, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Pavithira\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [0.36989715        nan 0.92175633 0.98746044        nan        nan
 0.36989715        nan 0.92175633 0.98746044        nan        nan
 0.95300633        nan 0.95929589 0.98433544        nan        nan
 0.95300633        nan 0.95929589 0.98433544        nan        nan
 0.96867089        nan 0.96871044 0.98125           nan        nan
 0.96867089        nan 0.96871044 0.98125           nan        nan
 0.97183544        nan 0.96550633 0.98125           nan        nan
 0.97183544        nan 0.96550633 0.98125           nan        nan]
  warnings.warn(

Training SVM...
Fitting 4 folds for each of 18 candidates, totalling 72 fits
Training DecisionTree...
Fitting 4 folds for each of 162 candidates, totalling 648 fits

C:\Users\Pavithira\anaconda3\Lib\site-packages\numpy\ma\core.py:2820: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,

Training RandomForest...
Fitting 4 folds for each of 216 candidates, totalling 864 fits
Training GradientBoosting...
Fitting 4 folds for each of 81 candidates, totalling 324 fits
Training XGBoost...
Fitting 4 folds for each of 81 candidates, totalling 324 fits
Training KNN...
Fitting 4 folds for each of 48 candidates, totalling 192 fits
Training BernoulliNB...
Fitting 4 folds for each of 9 candidates, totalling 36 fits
Time taken in grid search: 119.23 seconds

In [35]:
# Print Results
for algo_name, result in results.items():
    print(f"\n{algo_name}:")
    print(f"Best Parameters: {result['best_params']}")
    print(f"Accuracy: {result['accuracy']}")
    print(f"f1weighted: {result['f1weighted']}")
    print(f"precision: {result['precision']}")
    print(f"Recall: {result['recall']}")
    print(f"Roc_auc: {result['roc_auc']}")

LogisticRegression:
Best Parameters: {'C': 0.01, 'max_iter': 100, 'penalty': 'l2', 'solver': 'lbfgs'}
Accuracy: 1.0
f1weighted: 1.0
precision: 1.0
Recall: 1.0
Roc_auc: 1.0

SVM:
Best Parameters: {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}
Accuracy: 1.0
f1weighted: 1.0
precision: 1.0
Recall: 1.0
Roc_auc: 1.0

DecisionTree:
Best Parameters: {'criterion': 'entropy', 'max_depth': 20, 'min_samples_leaf': 5, 'min_samples_split': 5, 'splitter': 'random'}
Accuracy: 0.8875
f1weighted: 0.8877732793522266
precision: 0.9148936170212766
Recall: 0.8958333333333334
Roc_auc: 0.8854166666666667

RandomForest:
Best Parameters: {'ccp_alpha': 0.0, 'criterion': 'log_loss', 'max_depth': 10, 'max_features': 'sqrt', 'n_estimators': 150}
Accuracy: 0.9875
f1weighted: 0.9874652266404844
precision: 0.9795918367346939
Recall: 1.0
Roc_auc: 0.984375

GradientBoosting:
Best Parameters: {'learning_rate': 1, 'max_depth': 3, 'min_samples_split': 10, 'n_estimators': 100}
Accuracy: 1.0
f1weighted: 1.0
precision: 1.0
Recall: 1.0
Roc_auc: 1.0

XGBoost:
Best Parameters: {'learning_rate': 1, 'max_depth': 5, 'min_child_weight': 1, 'n_estimators': 100}
Accuracy: 0.9625
f1weighted: 0.962591093117409
precision: 0.9787234042553191
Recall: 0.9583333333333334
Roc_auc: 0.9635416666666667

KNN:
Best Parameters: {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}
Accuracy: 0.9875
f1weighted: 0.9875303643724695
precision: 1.0
Recall: 0.9791666666666666
Roc_auc: 0.9895833333333333

BernoulliNB:
Best Parameters: {'alpha': 0.1, 'binarize': 0.5}
Accuracy: 1.0
f1weighted: 1.0
precision: 1.0
Recall: 1.0
Roc_auc: 1.0

In [36]:
# Find best algorithm based on accuracy
best_algo_name = max(results, key=lambda k: results[k]['accuracy']) # As class is not imbalanced so i'm using accuracy to check the results.
best_model = results[best_algo_name]['best_model']

In [120]:
# Save the best model using pickle
filename = "CKD_best_model.pkl"
with open( filename, 'wb') as file:
    pickle.dump(best_model, file)
print(f"Best model ({best_algo_name}) saved to {filename}")

Best model (LogisticRegression) saved to CKD_best_model.pkl

In [122]:
# Load and Predict using the saved model
with open('CKD_best_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)
predictions = loaded_model.predict(X_test)
print("Predictions using loaded model:", predictions)

Predictions using loaded model: [0 1 0 1 1 1 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 0
 0 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0
 0 1 1 1 1 0]

In [124]:
y_test

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0])

In [128]:
from sklearn.metrics import classification_report, confusion_matrix

# Assuming you've chosen the best algorithm and made predictions
y_pred = best_model.predict(X_test)

# Generate Confusion Matrix
confusion_matrix= confusion_matrix(y_test,y_pred)
print("Confusion Matrix:\n", confusion_matrix)

# Generate Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

Confusion Matrix:
 [[32  0]
 [ 0 48]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        48

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80